---
# Source: wg-access-server/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "quickstart-wg-access-server"
  labels:
    helm.sh/chart: wg-access-server-v0.6.0
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  privateKey: ""
  adminUsername: "YWRtaW4="
  adminPassword: "clc1bVNKbGs1MnVaOUpiZUxVY2I="
---
# Source: wg-access-server/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quickstart-wg-access-server
  labels:
    helm.sh/chart: wg-access-server-v0.6.0
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |-
    vpn:
      cidrv6: 0
---
# Source: wg-access-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quickstart-wg-access-server-web
  labels:
    helm.sh/chart: wg-access-server-v0.6.0
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
---
# Source: wg-access-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quickstart-wg-access-server-wireguard
  labels:
    helm.sh/chart: wg-access-server-v0.6.0
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ipFamilyPolicy: SingleStack
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
      name: wireguard
  selector:
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
---
# Source: wg-access-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart-wg-access-server
  labels:
    helm.sh/chart: wg-access-server-v0.6.0
    app: wg-access-server
    app.kubernetes.io/name: wg-access-server
    app.kubernetes.io/instance: quickstart
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: wg-access-server
      app.kubernetes.io/name: wg-access-server
      app.kubernetes.io/instance: quickstart
  template:
    metadata:
      annotations:
        checksum/configmap: 3240f1610ddb40f38805a86a7d42883d4e86eda88412120dc5ae055947190a2d
        checksum/secret: 1467e5c5dd18b5fa07b6b9ee7ede1ae26a80c78c82b8253d8ad5832ffb07f01b
      labels:
        app: wg-access-server
        app.kubernetes.io/name: wg-access-server
        app.kubernetes.io/instance: quickstart
    spec:
      containers:
        - name: wg-access-server
          securityContext:
            capabilities:
              add: ['NET_ADMIN']
          image: "ghcr.io/freifunkmuc/wg-access-server:v0.6.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: wireguard
              containerPort: 51820
              protocol: UDP
          env:
            - name: WG_WIREGUARD_PORT
              value: "51820"
            - name: WG_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "quickstart-wg-access-server"
                  key: adminUsername
            - name: WG_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "quickstart-wg-access-server"
                  key: adminPassword
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
      volumes:
        - name: tun
          hostPath:
            type: 'CharDevice'
            path: /dev/net/tun
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: "quickstart-wg-access-server"
