name: Update Helm Chart
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  package_helm:
    name: Update and package Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run Helm update
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          pip3 install --upgrade -r scripts/requirements-update-helm.txt
          python3 scripts/update-helm.py
